version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: cadaviz-code-hub_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=Cadaviz_OrderDB
    networks:
      - cadaviz-code-hub_network
    restart: always

networks:
  cadaviz-code-hub_network:
    driver: bridge

volumes:
  mongo-data:
    driver: local